### ISSUE TITLE
Recommendation: `pls` under File Managers / Tools

### ISSUE THREAD

**Issue by dhruvkb** [cli-club/cli-club.github.io#1]
Firstly, cool idea for a website. Secondly, I would like to recommend a tool I maintain, [`pls`](https://pls.cli.rs) for inclusion under File Managers or Tools. `pls` is free and open-source, and the code is accessible on GitHub at https://github.com/pls-rs/pls.

**Comment by cli-club** [comment]
Thanks Dhruv, great recommendation, this has been added!

https://cli.club/#pls
