### ISSUE TITLE
Add `iamb` under Matrix clients

### ISSUE THREAD

**Issue by Kaamkiya** [cli-club/cli-club.github.io#2]
[iamb](https://github.com/ulyssa/iamb) is a Matrix client written in Rust with Vim-style keys. It supports threads, spaces, e2ee, and more.

I think it's pretty good, and it'd be a nice thing to see on the list.

(Note: I'm not affiliated with the project in any way.)

**Comment by cli-club** [comment]
Added! https://cli.club/#iamb
